"""Write python/manifest.json — the files the Playground mounts into Pyodide —
and tools/playground-examples.js from python/examples/*.py.

Run after changing anything under python/:   python python/make_manifest.py
"""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PACKAGES = ["mentorpi_sim", "rclpy", "builtin_interfaces", "std_msgs", "geometry_msgs", "sensor_msgs",
            "nav_msgs", "std_srvs", "example_interfaces", "tf2_ros", "rcl_interfaces", "cv_bridge", "sensor_msgs_py"]
MODULES = ["tf_transformations.py"]
NL = chr(10)


def main() -> None:
    files = list(MODULES)
    for pkg in PACKAGES:
        for p in sorted((ROOT / pkg).rglob("*")):
            if p.is_dir() or "__pycache__" in p.parts:
                continue
            if p.suffix in (".py", ".json"):
                files.append(p.relative_to(ROOT).as_posix())
    samples = sorted(p.relative_to(ROOT).as_posix() for p in (ROOT / "samples").glob("*.png"))
    h = hashlib.sha256()
    for rel in files + samples:
        h.update(rel.encode())
        h.update((ROOT / rel).read_bytes().replace(b"\r\n", b"\n"))
    out = {"version": h.hexdigest()[:12], "files": files, "samples": samples}
    (ROOT / "manifest.json").write_text(json.dumps(out, indent=1) + NL, encoding="utf-8", newline=NL)
    print("manifest: %d files + %d samples, version %s" % (len(files), len(samples), out["version"]))


def write_examples() -> None:
    """tools/playground-examples.js from python/examples/*.py (header: '# title:' / '# group:')."""
    items = []
    for p in sorted((ROOT / "examples").glob("*.py")):
        lines = p.read_text(encoding="utf-8").splitlines()
        head = {}
        body = []
        for ln in lines:
            m = re.match(r"^# (title|group): (.+)$", ln)
            if m and not body:
                head[m.group(1)] = m.group(2).strip()
            else:
                body.append(ln)
        while body and not body[0].strip():
            body.pop(0)
        items.append({"id": p.stem, "title": head.get("title", p.stem),
                      "group": head.get("group", "예제"), "code": NL.join(body) + NL})
    default = next((e["code"] for e in items if e["id"].startswith("03_")), items[0]["code"] if items else "")
    js = ("// generated by python/make_manifest.py from python/examples/*.py -- do not edit" + NL
          + "export const EXAMPLES = " + json.dumps(items, ensure_ascii=False, indent=1) + ";" + NL + NL
          + "export const DEFAULT_CODE = " + json.dumps(default, ensure_ascii=False) + ";" + NL)
    (ROOT.parent / "tools" / "playground-examples.js").write_text(js, encoding="utf-8", newline=NL)
    print("examples: %d" % len(items))


if __name__ == "__main__":
    main()
    write_examples()
